### PR TITLE
Update Spark version to 2.3.2

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
This PR aims to upgrade Spark to 2.3.2.

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
Hi, @arunmahadevan . Could you review and merge this?

**Review by arunmahadevan — APPROVED** [review]
+1

**Comment by arunmahadevan** [comment]
Thanks @dongjoon-hyun for the patch. Merged to master.

**Comment by dongjoon-hyun** [comment]
Thanks!

**Pull request merged**
